[2022-01-15 03:11:45,416] [tuya-openmq] Unexpected disconnection.16
2022-01-15 03:11:45,416 - ERROR    - tuya_iot: Unexpected disconnection.16
[2022-01-15 03:11:45,444] [tuya-openmq] Unexpected disconnection.16
2022-01-15 03:11:45,444 - ERROR    - tuya_iot: Unexpected disconnection.16
2022-01-15 03:12:05,484 - WARNING  - urllib3.connectionpool: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x737dad00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /api/6031048/store/
2022-01-15 03:12:25,509 - WARNING  - urllib3.connectionpool: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x737daa78>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /api/6031048/store/
